### ISSUE TITLE
Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true

### ISSUE THREAD

**Issue by thuy-econsys** [thuy-econsys/rails_app#6]
testing devise_invitable gem but specs are having issues with this line:
```ruby
# app/views/devise/mailer/invitation_instructions.html.erb

<p><%= t("devise.mailer.invitation_instructions.someone_invited_you", url: root_url) %></p>
```

the `default_url_options` are already set for **localhost:3000** like so: 

```ruby
# config/environments/development.rb

config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }
```

stacktrace:

```bash
     Failure/Error: <p><%= t("devise.mailer.invitation_instructions.someone_invited_you", url: root_url) %></p>
     
     ActionView::Template::Error:
       Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true
     # ./app/views/devise/mailer/invitation_instructions.html.erb:3:in `_app_views_devise_mailer_invitation_instructions_html_erb__4508318497893517322_70248849500460'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/devise-4.7.3/lib/devise/mailers/helpers.rb:19:in `devise_mail'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/devise_invitable-2.0.2/lib/devise_invitable/mailer.rb:9:in `invitation_instructions'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/devise-4.7.3/lib/devise/models/authenticatable.rb:200:in `send_devise_notification'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/devise_invitable-2.0.2/lib/devise_invitable/models.rb:210:in `deliver_invitation'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/devise_invitable-2.0.2/lib/devise_invitable/models.rb:163:in `block in invite!'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/devise_invitable-2.0.2/lib/devise_invitable/models.rb:152:in `invite!'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/devise_invitable-2.0.2/lib/devise_invitable/models.rb:327:in `_invite'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/devise_invitable-2.0.2/lib/devise_invitable/models.rb:333:in `invite!'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/devise_invitable-2.0.2/app/controllers/devise/invitations_controller.rb:80:in `invite_resource'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/devise_invitable-2.0.2/app/controllers/devise/invitations_controller.rb:19:in `create'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:38:in `call_app'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:26:in `block in call'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:26:in `call'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/railties-5.2.4.4/lib/rails/engine.rb:524:in `call'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/rack-test-1.1.0/lib/rack/test.rb:129:in `custom_request'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/rack-test-1.1.0/lib/rack/test.rb:66:in `post'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/capybara-3.33.0/lib/capybara/rack_test/browser.rb:70:in `process'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/capybara-3.33.0/lib/capybara/rack_test/browser.rb:45:in `process_and_follow_redirects'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/capybara-3.33.0/lib/capybara/rack_test/browser.rb:35:in `submit'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/capybara-3.33.0/lib/capybara/rack_test/form.rb:43:in `submit'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/capybara-3.33.0/lib/capybara/rack_test/node.rb:75:in `click'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/capybara-3.33.0/lib/capybara/rack_test/node.rb:137:in `block (2 levels) in <class:Node>'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/capybara-3.33.0/lib/capybara/node/element.rb:172:in `block in click'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/capybara-3.33.0/lib/capybara/node/element.rb:601:in `block in perform_click_action'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/capybara-3.33.0/lib/capybara/node/base.rb:83:in `synchronize'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/capybara-3.33.0/lib/capybara/node/element.rb:601:in `perform_click_action'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/capybara-3.33.0/lib/capybara/node/element.rb:171:in `click'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/capybara-3.33.0/lib/capybara/node/actions.rb:58:in `click_button'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/capybara-3.33.0/lib/capybara/session.rb:759:in `block (2 levels) in <class:Session>'
     # /Users/user/.rvm/gems/ruby-2.5.1/gems/capybara-3.33.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
     # ./spec/helpers/helpers.rb:26:in `send_invite'
     # ./spec/features/invite.rb:25:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # ArgumentError:
     #   Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true
     #   ./app/views/devise/mailer/invitation_instructions.html.erb:3:in `_app_views_devise_mailer_invitation_instructions_html_erb__4508318497893517322_70248849500460'
```

according to this article possibly a Rails issue: [Define host so absolute urls work in development and test | Ruby on Rails discussions](https://discuss.rubyonrails.org/t/define-host-so-absolute-urls-work-in-development-and-test/75085)

**Comment by thuy-econsys** [comment]
appears to be fixed by adding to both test and development configs: 

```ruby
Rails.application.configure do
  ...
  # Action Mailer
  config.action_mailer.default_url_options = { host: 'localhost:3000' } # for absolute urls in email
  config.action_mailer.asset_host = "http://localhost:3000" # for image URLs in HTML email

  # Allow generating absolute urls with routing url helpers.
  Rails.application.routes.default_url_options[:host] = 'localhost:3000'
```

by this commit https://github.com/thuy-econsys/rails_app/commit/1a81991d03cf610045abc1261cf57a07a78bfe5e
